dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 2.0.0
script:    
  - dotnet restore ./VaderSharp/VaderSharp.Test/VaderSharp.Test.csproj
  - dotnet test ./VaderSharp/VaderSharp.Test/VaderSharp.Test.csproj